name: App-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Get Gradle wrapper
          run: gradle wrapper

        - name: 构建 APK
          run: ./gradlew assembleRelease
          shell: bash
