name: AppBuildfjhfjh

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: 检出代码
          uses: actions/checkout@v4

        - name: 设置 JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: 设置 Android SDK
          uses: android-actions/setup-android@v3
          with:
            android-version: 'latest'

        - name: Gradle 构建
          run: ./gradlew assembleRelease
          shell: bash

        - name: 发布到 Release
          run: |
            for f in app/build/outputs/apk/release/*.apk; do
              if [ -f "$f" ]; then
                dir=$(dirname "$f")
                base=$(basename "$f" .apk)
                mv "$f" "$dir/${base}-${{ github.run_id }}.apk"
              fi
            done
          shell: bash
        - name: Upload Release
          uses: softprops/action-gh-release@v2
          with:
            files: app/build/outputs/apk/release/*-${{ github.run_id }}.apk
            tag_name: release-${{ github.run_number }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

